project_id = "xztsijmsttkwmzcrjhlk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.admin-create-user]
    verify_jwt = true
  [functions.admin-delete-user]
    verify_jwt = true
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-events]
    verify_jwt = false
  [functions.notify-enquiry-lead]
    verify_jwt = true
  [functions.notify-contact-lead]
    verify_jwt = true
  [functions.notify-footer-lead]
    verify_jwt = true
