project_id = "xztsijmsttkwmzcrjhlk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.admin-create-user]
    verify_jwt = true
  [functions.admin-delete-user]
    verify_jwt = true
